---

- set_fact:
    checkinstall_package: checkinstall-{{checkinstall_version}}-1.{{ansible_architecture}}.rpm
    checkinstall_disthome: /root/rpmbuild/RPMS/{{ansible_architecture}}

- name: install SELinux Python bindings required by Ansible "copy" module
  yum: name=libselinux-python
  sudo: yes

- name: copy pre-built Checkinstall package
  copy: src={{checkinstall_package}}
        dest={{checkinstall_disthome}}/
        owner=root group=root mode=0644
  sudo: yes

- name: install rpm handlers
  yum: name={{item}}
  with_items: [ rpm-build, rpmdevtools ]
  sudo: yes

- name: create rpm source trees
  command: rpmdev-setuptree
  args:
    creates: /root/rpmbuild
  sudo: yes

- name: install Checkinstall
  yum: name={{checkinstall_disthome}}/{{checkinstall_package}}
  sudo: yes

- name: test Checkinstall
  shell: checkinstall --version
  sudo: yes
  changed_when: False
