---

- include: apt.yml
  when: ansible_pkg_mgr == 'apt'

- include: el6.yml
  when: ansible_pkg_mgr == 'yum' and
        ansible_distribution == 'CentOS' and
        ansible_distribution_version|int == 6

- name: test checkinstall command
  shell: checkinstall --version
  sudo: yes
  register: result
  changed_when: False
  failed_when: ('checkinstall ' + checkinstall_version) not in result.stdout
